dataset:
  name: "custom" # 使用什么数据集，目前支持 cifar10、mnist 和 custom

  # MNIST 和 CIFAR 数据集的参数
  download: False   # 如果是 MNIST 或 CIFAR，是否下载数据集
  train: True # 如果是 MNIST 或 CIFAR，是否使用训练集

  data_path: "E:/data/celeba_64"  # 数据集存放路径

  # transform 的参数
  image_size: [ 64, 64 ]  # 图片大小

  # DataLoader 的参数
  batch_size: 128  # 批大小
  shuffle: True # 是否打乱数据
  drop_last: True # 是否丢弃最后一个 batch
  pin_memory: True  # 是否将数据保存在 pin memory 中
  num_workers: 0  # 读取数据的线程数

  # 自定义数据集的参数
  suffix: [ "png", "jpg" ]  # 自定义数据集中加载图片的后缀名

model:
  in_channels: 3  # 输入图片的通道数，如果是 MNIST，这里应该是 1
  out_channels: 3 # 输出图片的通道数，如果是 MNIST，这里应该是 1

loss:
  a: 1.5
  lambda_rec: 20
  lambda_idem: 20
  lambda_tight: 2.5

optimizer:
  lr: 0.0001
  betas: [ 0.5, 0.999 ]
