dataset:
  name: "custom" # what dataset is used，support cifar10, mnist and custom

  # MNIST and CIFAR dataset's parameters
  download: False   # whether to download the dataset
  train: True # whether to use the training set

  data_path: "E:/data/celeba_64"  # the path of the dataset, if MNIST or CIFAR, this parameter is the download path

  # transform's parameters
  image_size: [ 64, 64 ]  # image size

  # DataLoader's parameters
  batch_size: 128  # batch size
  shuffle: True # whether to shuffle the dataset
  drop_last: True # whether to drop the last batch
  pin_memory: True  # whether to use pin memory
  num_workers: 0  # the number of workers

  # custom dataset's parameters
  suffix: [ "png", "jpg" ]  # the suffix of the image

model:
  in_channels: 3  # input image's channel, if MNIST, this parameter is 1
  out_channels: 3 # output image's channel, if MNIST, this parameter is 1

loss:
  a: 1.5  # the parameter of the smooth loss in paper
  lambda_rec: 20  # the weight of the reconstruction loss in paper
  lambda_idem: 20 # the weight of the idempotent loss in paper
  lambda_tight: 2.5 # the weight of the tighten loss in paper

optimizer:
  lr: 0.0001  # learning rate
  betas: [ 0.5, 0.999 ] # the betas of Adam optimizer
